FROM node:22-alpine
WORKDIR /app
RUN npm install -g pnpm@10
COPY package.json pnpm-lock.yaml* ./
RUN pnpm config set fetch-timeout 600000
RUN pnpm config set fetch-retries 5
RUN pnpm install
COPY . .
EXPOSE 3000
CMD ["pnpm", "run", "dev"]